- name: Load variables for ARMv7 systems
  include_vars:
    file: armv7.yml
  when: ansible_architecture == 'armv7l'

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Setup Docker repository
  apt_repository:
    repo: "deb [arch={{ docker_package_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce-stable

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - "docker-ce={{ docker_version }}-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
      - "docker-ce-cli={{ docker_version }}-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"

- name: Add version pinning for Docker packages
  copy:
    content: |
            Package: docker-ce
            Pin: version {{ docker_version }}-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
            Pin-Priority: 1000

            Package: docker-ce-cli
            Pin: version {{ docker_version }}-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
            Pin-Priority: 1000
    dest: /etc/apt/preferences.d/docker
    owner: root
    group: root
    mode: 0644

- name: Start and enable Docker daemon
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

- name: Configure Docker daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Reload Docker service
